# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
executors:
  node:
    docker:
      - image: cimg/node:lts
  git:
    docker:
      - image: alpine/git

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-cache-{{ .Branch }}
            - node-cache
      - run: npm install
      - save_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: npm run lint
      - run:
          name: Unit tests
          command: npm run test:unit:ci
          when: always
      - store_artifacts:
          path: ./junit.unit.xml
      - store_test_results:
          path: ./junit.unit.xml
      - run:
          name: E2e tests
          command: npm run test:e2e:ci
          when: always
      - store_artifacts:
          path: ./junit.e2e.xml
      - store_test_results:
          path: ./junit.e2e.xml
  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: npm run build
      - store_artifacts:
          path: ./dist
      - persist_to_workspace:
          root: .
          paths:
            - ./dist
  docs:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: npm run doc:for-current-version
      - store_artifacts:
          path: ./docs
      - persist_to_workspace:
          root: .
          paths:
            - ./docs
  check-releaseable:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Maybe abort ci
          command: |
            if ! ./.circleci/extract-release-message.sh; then
              curl --request POST \
                --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel \
                --header "Circle-Token: ${CIRCLE_TOKEN}"
             else
              echo "Would publish $(./.circleci/extract-release-message.sh)"
            fi
      - run:
          name: Check files
          command: npm publish --dry-run
  publish-git-tag:
    executor: git
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Config git
          command: |
            git config --global user.email "Scitizen-publish-bot@users.noreply.github.com"
            git config --global user.name "Scitizen-publish-bot"
      - run:
          name: Push docs & tag
          command: |
            git add --force docs
            git commit --amend -m "ci(release): publish v$(./.circleci/extract-release-message.sh)

            [skip ci]"
            git remote set-url origin https://$CIRCLE_PROJECT_USERNAME:$GITHUB_AUTH_SECRET@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            git push --follow-tags --set-upstream origin $CIRCLE_BRANCH
  publish-npm:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: echo "TODO"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  check: # Workflow ran on all branches except `main`
    unless:
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
  publish: # Workflow ran only on `main`
    when:
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - install

      - test:
          requires:
            - install
      - build:
          requires:
            - install

      - check-releaseable:
          filters:
            branches:
              only:
                - master
                - main
          requires:
            - build
            - test
      - Confirm new release:
          type: approval
          requires:
            - Check files

      - docs:
          requires:
            - Confirm new release
      - publish-npm:
          requires:
            - Confirm new release

      - publish-git-tag:
          requires:
            - docs
            - publish-npm
